#pragma config(Motor,  port1,           frick,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

repeat(forever){
	moveMotor(port1, 1, seconds, 127);
	moveMotor(port1, 1, seconds, -127);


}


}
