#pragma config(Motor,  port2,           backright,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           backleft,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          clawboi,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1==1)
{

	motor[backright] = vexRT[2];
	motor[port3] = vexRT[1];


	if(vexRT[Btn6U] == 1)
	{
		motor[port10] = 127;
	}

	else if (vexRT[Btn6D] == 1)
	{
		motor[port10] = -127;
	}

	else
	{
		motor[port10] = 0;
	}


}

}
