#pragma config(Motor,  port5,           frontleft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           backleft,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           backright,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           frontright,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           liftbitch,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

repeat (forever){

setMotor(frontright, 127);
setMotor(backright, 127);
setMotor(backleft, 127);
setMotor(frontleft, 127);
moveMotor(liftbitch, 1, seconds, 50);
moveMotor(liftbitch, 1, seconds, -50);
setMotor(frontright, -127);
setMotor(backright, -127);
setMotor(backleft, -127);
setMotor(frontleft, -127);

}

}
