#pragma config(Motor,  port5,           frontleft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           backleft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           backright,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           frontright,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           lift,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1==1)
{

	motor[backright] = vexRT[1];
	motor[frontright] = vexRT[1];
	motor[backleft] = vexRT[2];
	motor[frontleft] = vexRT[2];


	if(vexRT[Btn6U] == 1)
	{
		motor[lift] = 127;
	}

	else if (vexRT[Btn6D] == 1)
	{
		motor[lift] = -127;
	}

	else
	{
		motor[lift] = 0;
	}


}

}
