#pragma config(Motor,  port2,           lift,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           lift2,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1==1) {

setMotor(lift, -127);
setMotor(lift2, 127);

}

}
