#pragma config(Motor,  port2,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontleft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           backleft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           backright,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           frontright,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* compiled for vex 2.0 cortex system, using natural language pltw */


task main()
{

	while (1==1)
	{


		/* assign movement to tires */

		motor[backright] = vexRT[1];
		motor[frontright] = vexRT[1];
		motor[backleft] = vexRT[2];
		motor[frontleft] = vexRT[2];


		/* assign right bumper to lift mechanism */

		if(vexRT[Btn6U] == 1)
		{
			motor[lift] = 127;
		}

		else if (vexRT[Btn6D] == 1)
		{
			motor[lift] = -127;
		}

		else
		{
			motor[lift] = 0;
		}


		/* assign left bumper to claw	*/

		if(vexRT[Btn5U] == 1)
		{
			motor[claw] = 127;
		}

		else if (vexRT[Btn5D] == 1)
		{
			motor[claw] = -127;
		}

		else
		{
			motor[claw] = 0;
		}


	}

}


/* this code has super cow powers! */
